### ISSUE TITLE
`Controller as` support?

### ISSUE THREAD

**Issue by JasonMore** [AngularAgility/AngularAgility#100]
Angular agility is sad when I try to use `Controller as` http://plnkr.co/edit/6ikYLTrV5wqgkBaqCGK5?p=preview

`
<body ng-controller="main as MainCtrl">
  <div ng-form="main.exampleForm" class="form-horizontal">

```
<!-- EMAIL -->
<input type="email" aa-field-group="person.email" required/>
<!--/ EMAIL -->

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-3">
    <button aa-submit-form="save()" class="btn btn-default">Save</button>
  </div>
</div>
```

  </div>
</body>
`

And the error
`Error: [ng:areq] Argument 'main' is not a function, got undefined`

The offending line is
`line 1136: return $delegate.apply(this, arguments);`

**Comment by shanemgrey** [comment]
@JasonMore 
Shouldn't it be   
```<body ng-controller="MainCtrl as main"> ```  
instead of your   
```<body ng-controller="main as MainCtrl"> ```  
?

**Comment by npearson72** [comment]
Yeah, he's got it reversed

**Comment by adjohnson916** [comment]
I also can't get the module to understand my form `name` attribute pointing to my controller with the "controller as" syntax (e.g. `<form name="$ctrl.form">` instead of just `<form name="form">`) so that I can access the `FormController` as `form` on my controller directly rather than hacking around it e.g. by having to inject `$scope` and use `$scope.form` or use the `$postLink` lifecycle hook on my component to assign `ctrl.form = $scope.form`.

**Comment by johnculviner** [comment]
Yeah this bit was written before `controller as` was even a thing. Would be happy to accept a PR if someone can fix it!
