### ISSUE TITLE
how to create a custom validator function?

### ISSUE THREAD

**Issue by jmcmichael** [AngularAgility/AngularAgility#110]
I would like to create a validator for a field that compares the field's content to another scope variable. The use case is that I would like to verify that the user has actually made a change to a field before submitting. I'm thinking the best way to do that is just to compare the field's value to a stored copy of the original value (also in the same scope). I'm currently using the external form config method, and was hoping that the 'validators' attribute could take a function as well as the various built-in validators, but in perusing the code it doesn't look like that would work.

Do you provide this functionality, or am I going about this in the wrong way?

Thanks for such an incredibly useful set of ng form directives, I can already tell I'm going to be using them extensively throughout our application.

**Comment by johnculviner** [comment]
Yeah nothing that I'm aware of. Generally when stuff gets difficult (maybe 5-10% of the time) I just shrug and say "I'll just do it manually" rather than use AA. That tends to hit the sweet spot of productivity and maintainable code. Glad you like the library and let me know if you come up with anything cool to solve the issue or have an idea for a PR to make it better. Thanks!

**Comment by jmcmichael** [comment]
Cool, thanks!
