### ISSUE TITLE
aaIsLoading and multiple forms

### ISSUE THREAD

**Issue by jmcmichael** [AngularAgility/AngularAgility#112]
In one of my directives, I'm using $root.aaIsLoading to show a spinner on a form submit button while the request is pending. This works fabulously. However, I have another directive with two sets of buttons, and when I hit submit on either set, the spinners show on both submit buttons instead of the one clicked.

I'm thinking of just adding a variable that keeps track of which button was pressed and then adding a && buttonClicked = [this button name] to the ng-show expression. Is there a less kludgey pattern for handling this situation?

**Comment by johnculviner** [comment]
Yeah I can't think of anything off the top of my head. $rootScope.aaIsLoading is very global so if you want to track on a button basis something like that would work well. You could probably compartmentalize that pattern into a directive 'loadingButton' or something that only shows the loading indicator when IT was the button that was clicked otherwise it doesn't. Thoughts?

**Comment by johnculviner** [comment]
this is more of a question than a bug
