### ISSUE TITLE
Validation message on two inputs with same name

### ISSUE THREAD

**Issue by deividfortuna** [AngularAgility/AngularAgility#137]
Hello,

The "form" on jsfiddle have two input with same name, but they are not showing at the same time. When we change the "input" that is displaying the validation message stay unstable, sometimes working (showing the validation message) and sometimes not.

Take a look please: https://jsfiddle.net/deividfortuna/f6gh434q/

Sorry about my bad english.
Thanks.

**Comment by johnculviner** [comment]
Interesting, not sure how that is happening. I think there might be a race condition because both inputs have the same name (which is what angular and also angularagility uses to key form fields)

Can you make the fields have different names in your application? That would be my solution probably....

There are some unfortunate $timeout s in AA to get everything to work properly that could be causing it...

**Comment by deividfortuna** [comment]
Thanks for the answer. 
I tried to quickly look for what was causing it, but unfortunately I have not found.  I'll see if it is possible to use different input names

**Comment by johnculviner** [comment]
No problem, different input names or different forms are gonna be your solution. I bet you can find a way to do one or the other :)
